version: '2'
services:
  db:
    image: postgres:alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - /.data:/var/lib/postgresql/data
  shop:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - ./../rails-app:/home/app
      - ./../rails-app/bundle:/bundle
    links:
      - db:db
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - shop:shop
