version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - 5432:5432
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - $PWD:/home/app
    ports:
      - 3000:3000
    links:
      - db
    # This tells the web container to mount the `bundle` images'
    # /bundle volume to the `web` containers /bundle path.
    volumes_from:
      - bundle
  # You may need to run `docker-compose build web` before this works.
  bundle:
    image: dungho/rails5_web:1.0
    volumes:
      - /bundle